### ISSUE TITLE
Question: Termination-safety

### ISSUE THREAD

**Issue by ratanasov1** [davedoesdev/shared-memory-disruptor#15]
It is interesting to see disruptor in shared memory.
 
Is there termination-safety of producers and consumers? I.e. what will happen to the system if a producer crashes/is killed in between the claim and commit; or with consumer tracking a consumer that dies and never updates its position?

**Comment by davedoesdev** [comment]
@ratanasov1 there is no termination safety. Do you have any ideas on how to achieve it?
Timeout? Write process ID into the disruptor and check if it's still alive?

**Comment by ratanasov1** [comment]
@davedoesdev Thanks for replying. With Disruptor designed so carefully I have no idea how to detect this condition and how to report it to client code in a sensible way. Timeout is an option, but what will happen to latency? Writing PID into the disruptor, there must be some policy how to reuse that slot, i.e. some clean up agent.

**Comment by davedoesdev** [comment]
Yes, even writing PID will affect latency.
I wonder if this just has to be delegated to an application level?
Maybe you'd just have a supervisor which monitors all the processes involved and kills them all when any exit or stop responding to ping messages.

**Comment by davedoesdev** [comment]
On reflection I think this should be left to an application-level supervisor.

**Comment by ratanasovvmw** [comment]
You may take a look at https://github.com/vmware-labs/advanced-same-machine-interprocess-communication-protocol-suite which is a solution that is termination safe.

**Comment by davedoesdev** [comment]
@ratanasovvmw thanks for the pointer, looks good!
